FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}

# Copy requirements
COPY apps/api/requirements.txt .
RUN pip install -r requirements.txt

# Copy application code
COPY apps/api/* ./

# Set Lambda handler
CMD [ "main.handler" ]
